import { NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import connectDB from '@/lib/db';
import { User } from '@/lib/models/User';
import { Doctor } from '@/lib/models/Doctor';
import { Patient } from '@/lib/models/Patient';

export async function GET() {
  try {
    await connectDB();

    // 1. Clear existing users to prevent duplicates (Optional, remove if you want to keep old data)
    await User.deleteMany({});

    // 2. Hash the "admin" password using your local bcrypt setup
    const hashedPassword = await bcrypt.hash("admin", 10);

    const doctorsData = [
      { firstname: "George", lastname: "Clooney", email: "george@doctor.com", phoneNumber: "+639171000001", role: "doctor", profileImage: "https://i.imgur.com/83u6G7p.jpeg", licenseNumber: "MD-01", specialty: "Cardiology", experience: 25, bio: "Veteran cardiologist.", availableSlots: [{ dayOfWeek: "Monday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Halle", lastname: "Berry", email: "halle@doctor.com", phoneNumber: "+639171000002", role: "doctor", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Halle_Berry_by_Gage_Skidmore_2.jpg/400px-Halle_Berry_by_Gage_Skidmore_2.jpg", licenseNumber: "MD-02", specialty: "Dermatology", experience: 18, bio: "Board-certified dermatologist.", availableSlots: [{ dayOfWeek: "Tuesday", startTime: "10:00", endTime: "16:00" }], blockedDates: [] },
      { firstname: "Denzel", lastname: "Washington", email: "denzel@doctor.com", phoneNumber: "+639171000003", role: "doctor", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Denzel_Washington_2018.jpg/400px-Denzel_Washington_2018.jpg", licenseNumber: "MD-03", specialty: "Neurology", experience: 30, bio: "Specializes in migraines.", availableSlots: [{ dayOfWeek: "Wednesday", startTime: "08:00", endTime: "14:00" }], blockedDates: [] },
      { firstname: "Lucy", lastname: "Liu", email: "lucy@doctor.com", phoneNumber: "+639171000004", role: "doctor", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lucy_Liu_2019_by_Glenn_Francis.jpg/400px-Lucy_Liu_2019_by_Glenn_Francis.jpg", licenseNumber: "MD-04", specialty: "Pediatrics", experience: 15, bio: "Focus on childhood development.", availableSlots: [{ dayOfWeek: "Thursday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Idris", lastname: "Elba", email: "idris@doctor.com", phoneNumber: "+639171000005", role: "doctor", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Idris_Elba_2014.jpg/400px-Idris_Elba_2014.jpg", licenseNumber: "MD-05", specialty: "Orthopedics", experience: 22, bio: "Sports medicine surgeon.", availableSlots: [{ dayOfWeek: "Friday", startTime: "07:00", endTime: "15:00" }], blockedDates: [] },
      { firstname: "Sandra", lastname: "Oh", email: "sandra@doctor.com", phoneNumber: "+639171000006", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=sandra", licenseNumber: "MD-06", specialty: "Psychiatry", experience: 19, bio: "Anxiety and CBT specialist.", availableSlots: [{ dayOfWeek: "Monday", startTime: "11:00", endTime: "19:00" }], blockedDates: [] },
      { firstname: "Oscar", lastname: "Isaac", email: "oscar@doctor.com", phoneNumber: "+639171000007", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=oscar", licenseNumber: "MD-07", specialty: "Gastroenterology", experience: 14, bio: "Treats IBS and gut health.", availableSlots: [{ dayOfWeek: "Tuesday", startTime: "08:00", endTime: "16:00" }], blockedDates: [] },
      { firstname: "Viola", lastname: "Davis", email: "viola@doctor.com", phoneNumber: "+639171000008", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=viola", licenseNumber: "MD-08", specialty: "Oncology", experience: 26, bio: "Targeted immunotherapy.", availableSlots: [{ dayOfWeek: "Wednesday", startTime: "10:00", endTime: "18:00" }], blockedDates: [] },
      { firstname: "Ryan", lastname: "Reynolds", email: "ryan@doctor.com", phoneNumber: "+639171000009", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=ryan", licenseNumber: "MD-09", specialty: "General Practice", experience: 12, bio: "Annual checkups and bloodwork.", availableSlots: [{ dayOfWeek: "Thursday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Margot", lastname: "Robbie", email: "margot@doctor.com", phoneNumber: "+639171000010", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=margot", licenseNumber: "MD-10", specialty: "Endocrinology", experience: 10, bio: "Hormone therapy and diabetes.", availableSlots: [{ dayOfWeek: "Friday", startTime: "09:00", endTime: "15:00" }], blockedDates: [] },
      { firstname: "Brad", lastname: "Pitt", email: "brad@doctor.com", phoneNumber: "+639171000011", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=brad", licenseNumber: "MD-11", specialty: "Urology", experience: 21, bio: "Kidney stones and reproductive health.", availableSlots: [{ dayOfWeek: "Monday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Angelina", lastname: "Jolie", email: "angelina@doctor.com", phoneNumber: "+639171000012", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=angelina", licenseNumber: "MD-12", specialty: "Rheumatology", experience: 24, bio: "Autoimmune disease specialist.", availableSlots: [{ dayOfWeek: "Tuesday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Morgan", lastname: "Freeman", email: "morgan@doctor.com", phoneNumber: "+639171000013", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=morgan", licenseNumber: "MD-13", specialty: "Pulmonology", experience: 35, bio: "Asthma and COPD expert.", availableSlots: [{ dayOfWeek: "Wednesday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Julia", lastname: "Roberts", email: "julia@doctor.com", phoneNumber: "+639171000014", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=julia", licenseNumber: "MD-14", specialty: "Nephrology", experience: 20, bio: "Kidney care and dialysis.", availableSlots: [{ dayOfWeek: "Thursday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Tom", lastname: "Cruise", email: "tom@doctor.com", phoneNumber: "+639171000015", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=tom", licenseNumber: "MD-15", specialty: "Hematology", experience: 18, bio: "Blood disorders and anemia.", availableSlots: [{ dayOfWeek: "Friday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Nicole", lastname: "Kidman", email: "nicole@doctor.com", phoneNumber: "+639171000016", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=nicole", licenseNumber: "MD-16", specialty: "Allergy & Immunology", experience: 16, bio: "Severe allergies and asthma.", availableSlots: [{ dayOfWeek: "Monday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Leonardo", lastname: "DiCaprio", email: "leonardo@doctor.com", phoneNumber: "+639171000017", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=leonardo", licenseNumber: "MD-17", specialty: "Infectious Disease", experience: 14, bio: "Travel medicine and viral infections.", availableSlots: [{ dayOfWeek: "Tuesday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Charlize", lastname: "Theron", email: "charlize@doctor.com", phoneNumber: "+639171000018", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=charlize", licenseNumber: "MD-18", specialty: "Geriatrics", experience: 17, bio: "Elderly care and longevity.", availableSlots: [{ dayOfWeek: "Wednesday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Will", lastname: "Smith", email: "will@doctor.com", phoneNumber: "+639171000019", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=will", licenseNumber: "MD-19", specialty: "Ophthalmology", experience: 22, bio: "Vision correction surgeries.", availableSlots: [{ dayOfWeek: "Thursday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] },
      { firstname: "Meryl", lastname: "Streep", email: "meryl@doctor.com", phoneNumber: "+639171000020", role: "doctor", profileImage: "https://i.pravatar.cc/150?u=meryl", licenseNumber: "MD-20", specialty: "ENT", experience: 30, bio: "Ear, nose, and throat specialist.", availableSlots: [{ dayOfWeek: "Friday", startTime: "09:00", endTime: "17:00" }], blockedDates: [] }
    ].map(d => ({ ...d, password: hashedPassword }));

    const patientsData = [
      { firstname: "Tom", lastname: "Hanks", email: "tom@patient.com", phoneNumber: "+639172000001", role: "patient", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Tom_Hanks_TIFF_2019.jpg/400px-Tom_Hanks_TIFF_2019.jpg", dateOfBirth: "1956-07-09T00:00:00Z", gender: "male", bloodType: "O+", height: 183, weight: 85, allergies: [], medicalHistory: ["Diabetes"] },
      { firstname: "Zendaya", lastname: "Coleman", email: "zendaya@patient.com", phoneNumber: "+639172000002", role: "patient", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Zendaya_-_2019_by_Glenn_Francis.jpg/400px-Zendaya_-_2019_by_Glenn_Francis.jpg", dateOfBirth: "1996-09-01T00:00:00Z", gender: "female", bloodType: "A-", height: 178, weight: 59, allergies: ["Peanuts"], medicalHistory: [] },
      { firstname: "Keanu", lastname: "Reeves", email: "keanu@patient.com", phoneNumber: "+639172000003", role: "patient", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Reeves_at_the_2014_Comic_Con_International_2.jpg/400px-Reeves_at_the_2014_Comic_Con_International_2.jpg", dateOfBirth: "1964-09-02T00:00:00Z", gender: "male", bloodType: "B+", height: 186, weight: 79, allergies: [], medicalHistory: ["Shoulder Surgery"] },
      { firstname: "Florence", lastname: "Pugh", email: "florence@patient.com", phoneNumber: "+639172000004", role: "patient", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Florence_Pugh_at_the_2019_Comic-Con_International.jpg/400px-Florence_Pugh_at_the_2019_Comic-Con_International.jpg", dateOfBirth: "1996-01-03T00:00:00Z", gender: "female", bloodType: "AB+", height: 162, weight: 57, allergies: ["Dust"], medicalHistory: ["Asthma"] },
      { firstname: "Timothee", lastname: "Chalamet", email: "timothee@patient.com", phoneNumber: "+639172000005", role: "patient", profileImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Timothee_Chalamet_2017_Berlin_Film_Festival.jpg/400px-Timothee_Chalamet_2017_Berlin_Film_Festival.jpg", dateOfBirth: "1995-12-27T00:00:00Z", gender: "male", bloodType: "O-", height: 178, weight: 68, allergies: [], medicalHistory: [] },
      { firstname: "Anya", lastname: "Taylor-Joy", email: "anya@patient.com", phoneNumber: "+639172000006", role: "patient", profileImage: "https://i.pravatar.cc/150?u=anya", dateOfBirth: "1996-04-16T00:00:00Z", gender: "female", bloodType: "A+", height: 173, weight: 55, allergies: ["Lactose"], medicalHistory: ["Anemia"] },
      { firstname: "Ryan", lastname: "Gosling", email: "ryan@patient.com", phoneNumber: "+639172000007", role: "patient", profileImage: "https://i.pravatar.cc/150?u=ryan_g", dateOfBirth: "1980-11-12T00:00:00Z", gender: "male", bloodType: "B-", height: 184, weight: 80, allergies: [], medicalHistory: ["Hypertension"] },
      { firstname: "Scarlett", lastname: "Johansson", email: "scarlett@patient.com", phoneNumber: "+639172000008", role: "patient", profileImage: "https://i.pravatar.cc/150?u=scarlett", dateOfBirth: "1984-11-22T00:00:00Z", gender: "female", bloodType: "O+", height: 160, weight: 57, allergies: ["Pollen"], medicalHistory: [] },
      { firstname: "Chris", lastname: "Evans", email: "chris@patient.com", phoneNumber: "+639172000009", role: "patient", profileImage: "https://i.pravatar.cc/150?u=chris_e", dateOfBirth: "1981-06-13T00:00:00Z", gender: "male", bloodType: "B+", height: 183, weight: 88, allergies: [], medicalHistory: ["Torn ACL"] },
      { firstname: "Emily", lastname: "Blunt", email: "emily@patient.com", phoneNumber: "+639172000010", role: "patient", profileImage: "https://i.pravatar.cc/150?u=emily", dateOfBirth: "1983-02-23T00:00:00Z", gender: "female", bloodType: "A-", height: 171, weight: 56, allergies: ["Penicillin"], medicalHistory: ["Migraines"] },
      { firstname: "Cillian", lastname: "Murphy", email: "cillian@patient.com", phoneNumber: "+639172000011", role: "patient", profileImage: "https://i.pravatar.cc/150?u=cillian", dateOfBirth: "1976-05-25T00:00:00Z", gender: "male", bloodType: "O-", height: 175, weight: 70, allergies: [], medicalHistory: [] },
      { firstname: "Gal", lastname: "Gadot", email: "gal@patient.com", phoneNumber: "+639172000012", role: "patient", profileImage: "https://i.pravatar.cc/150?u=gal", dateOfBirth: "1985-04-30T00:00:00Z", gender: "female", bloodType: "B+", height: 178, weight: 58, allergies: ["Ibuprofen"], medicalHistory: [] },
      { firstname: "Michael", lastname: "Jordan", email: "michael@patient.com", phoneNumber: "+639172000013", role: "patient", profileImage: "https://i.pravatar.cc/150?u=michael", dateOfBirth: "1963-02-17T00:00:00Z", gender: "male", bloodType: "A+", height: 198, weight: 98, allergies: [], medicalHistory: ["Knee Surgery"] },
      { firstname: "Rebecca", lastname: "Ferguson", email: "rebecca@patient.com", phoneNumber: "+639172000014", role: "patient", profileImage: "https://i.pravatar.cc/150?u=rebecca", dateOfBirth: "1983-10-19T00:00:00Z", gender: "female", bloodType: "O+", height: 170, weight: 59, allergies: [], medicalHistory: [] },
      { firstname: "Robert", lastname: "Downey", email: "robert@patient.com", phoneNumber: "+639172000015", role: "patient", profileImage: "https://i.pravatar.cc/150?u=robert", dateOfBirth: "1965-04-04T00:00:00Z", gender: "male", bloodType: "AB+", height: 174, weight: 78, allergies: [], medicalHistory: ["Acid Reflux"] },
      { firstname: "Brie", lastname: "Larson", email: "brie@patient.com", phoneNumber: "+639172000016", role: "patient", profileImage: "https://i.pravatar.cc/150?u=brie", dateOfBirth: "1989-10-01T00:00:00Z", gender: "female", bloodType: "A-", height: 170, weight: 58, allergies: ["Latex"], medicalHistory: [] },
      { firstname: "Chris", lastname: "Hemsworth", email: "chris.h@patient.com", phoneNumber: "+639172000017", role: "patient", profileImage: "https://i.pravatar.cc/150?u=chris_h", dateOfBirth: "1983-08-11T00:00:00Z", gender: "male", bloodType: "O+", height: 190, weight: 91, allergies: [], medicalHistory: [] },
      { firstname: "Natalie", lastname: "Portman", email: "natalie@patient.com", phoneNumber: "+639172000018", role: "patient", profileImage: "https://i.pravatar.cc/150?u=natalie", dateOfBirth: "1981-06-09T00:00:00Z", gender: "female", bloodType: "B-", height: 160, weight: 50, allergies: [], medicalHistory: [] },
      { firstname: "Mark", lastname: "Ruffalo", email: "mark@patient.com", phoneNumber: "+639172000019", role: "patient", profileImage: "https://i.pravatar.cc/150?u=mark", dateOfBirth: "1967-11-22T00:00:00Z", gender: "male", bloodType: "O-", height: 173, weight: 72, allergies: [], medicalHistory: [] },
      { firstname: "Anne", lastname: "Hathaway", email: "anne@patient.com", phoneNumber: "+639172000020", role: "patient", profileImage: "https://i.pravatar.cc/150?u=anne", dateOfBirth: "1982-11-12T00:00:00Z", gender: "female", bloodType: "A+", height: 173, weight: 59, allergies: [], medicalHistory: [] }
    ].map(p => ({ ...p, password: hashedPassword }));

    // 3. Insert into Database safely
    await Doctor.insertMany(doctorsData);
    await Patient.insertMany(patientsData);

    return NextResponse.json({ message: "Successfully seeded 40 users with password 'admin'" });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}